name: Develop Branch Workflow

on:
  push:
    branches: [ develop ]
    paths-ignore:
    - '**/*.md'
    - 'LICENSE'
    - '.github/**'
    - '.gitignore'
    
jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: Dev
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout devops repo
        uses: actions/checkout@v3
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables.sh
        env:
          ENV_VAR_PREFIX: EASEY
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_DEV_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_DEV_DEPLOYMENT_SVC_PWD }}
      - name: Init Application
        run: devops/scripts/cf-app-init.sh
      - name: Deploy
        run: devops/scripts/deploy.sh
