name: Release Branch Workflow

on:
  push:
    branches: [ develop, release/* ]
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - '.github/**'
      - '.gitignore'

jobs:
  DEV-Deployment:
    runs-on: ubuntu-latest
    environment:
      name: Dev
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout devops repo
        uses: actions/checkout@v3
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables-noTag.sh DEV
        env:
          ENV_VAR_PREFIX: EASEY
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_DEV_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_DEV_DEPLOYMENT_SVC_PWD }}
      - name: Init Application
        run: devops/scripts/cf-app-init.sh
      - name: Deploy
        run: devops/scripts/deploy.sh

  CDC-Deployment:
    runs-on: ubuntu-latest
    environment:
      name: CDC
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout devops repo
        uses: actions/checkout@v3
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables-noTag.sh CDC
        env:
          ENV_VAR_PREFIX: EASEY
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_CDC_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_CDC_DEPLOYMENT_SVC_PWD }}
      - name: Init Application
        run: devops/scripts/cf-app-init.sh
      - name: Deploy
        run: devops/scripts/deploy.sh

  TEST-Deployment:
    runs-on: ubuntu-latest
    environment:
      name: Test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout devops repo
        uses: actions/checkout@v3
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables-noTag.sh TEST
        env:
          ENV_VAR_PREFIX: EASEY
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_TST_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_TST_DEPLOYMENT_SVC_PWD }}
      - name: Init Application
        run: devops/scripts/cf-app-init.sh
      - name: Deploy
        run: devops/scripts/deploy.sh

  BETA-Deployment:
    runs-on: ubuntu-latest
    environment:
      name: Beta
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout devops repo
        uses: actions/checkout@v3
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables-noTag.sh BETA
        env:
          ENV_VAR_PREFIX: EASEY
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_BETA_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_BETA_DEPLOYMENT_SVC_PWD }}
      - name: Init Application
        run: devops/scripts/cf-app-init.sh
      - name: Deploy
        run: devops/scripts/deploy.sh

  STG-Deployment:
    runs-on: ubuntu-latest
    environment:
      name: Staging
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout devops repo
        uses: actions/checkout@v3
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables-noTag.sh STAGE
        env:
          ENV_VAR_PREFIX: EASEY
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_STG_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_STG_DEPLOYMENT_SVC_PWD }}
      - name: Init Application
        run: devops/scripts/cf-app-init.sh
      - name: Deploy
        run: devops/scripts/deploy.sh


  PERF-Deployment:
    runs-on: ubuntu-latest
    environment:
      name: Performance
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout devops repo
        uses: actions/checkout@v3
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables-noTag.sh PERF
        env:
          ENV_VAR_PREFIX: EASEY
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_PERF_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_PERF_DEPLOYMENT_SVC_PWD }}
      - name: Init Application
        run: devops/scripts/cf-app-init.sh
      - name: Deploy
        run: devops/scripts/deploy.sh
